# One small stream per terminal feature; each starts from a cleared screen.
import os, sys
E = '\x1b'; C = E + '['
T = {
 'sgr-attrs':        C+'1mB'+C+'22;3mI'+C+'23;4mU'+C+'24;7mR'+C+'27;9mS'+C+'0mN',
 'sgr-16':           ''.join(C+'%dm%d'%(c,c) for c in list(range(30,38))+list(range(40,48))+list(range(90,98))+list(range(100,108)))+C+'0m',
 'sgr-256':          ''.join(C+'38;5;%dmx'%c for c in range(0,256,17))+C+'0m',
 'sgr-truecolor':    C+'38;2;255;0;0mr'+C+'48;2;0;0;200mb'+C+'38;2;0;0;5mt'+C+'0m',
 'sgr-colon':        C+'38:2::10:20:30mc'+C+'4:3mu'+C+'0m',
 'wrap-pending':     'W'*80+'X',
 'wrap-off':         C+'?7l'+'N'*85+C+'?7h'+'!',
 'wide-mid':         'ab中文cd',
 'wide-at-margin':   C+'1;80H'+'中'+'x',
 'wide-overwrite':   '中文'+C+'1;2H'+'x',
 'emoji':            'a😀b',
 'combining':        'é à́ ẍ',
 'tabs-default':     'a\tb\tc',
 'tabs-set-clear':   C+'3g'+C+'1;10H'+E+'H'+C+'1;30H'+E+'H'+'\r'+'1\t2\t3',
 'tab-back':         C+'1;40H'+C+'2Z'+'x'+C+'2I'+'y',
 'insert-char':      '0123456789'+C+'1;3H'+C+'2@',
 'delete-char':      '0123456789'+C+'1;3H'+C+'2P',
 'insert-mode':      'abcdef'+C+'1;3H'+C+'4h'+'XY'+C+'4l',
 'erase-line':       'aaaaaaaaaa'+C+'1;5H'+C+'0K'+'\r\n'+'bbbbbbbbbb'+C+'2;5H'+C+'1K'+'\r\n'+'cccccccccc'+C+'2K',
 'erase-chars':      'abcdefgh'+C+'1;3H'+C+'3X',
 'erase-display-0':  ('line\r\n'*5)+C+'3;2H'+C+'0J',
 'erase-display-1':  ('line\r\n'*5)+C+'3;2H'+C+'1J',
 'bg-erase-line':    C+'44m'+C+'K'+C+'0m',
 'bg-erase-display': C+'44m'+C+'2J'+C+'0m',
 'bg-erase-below':   C+'44m'+C+'5;1H'+C+'J'+C+'0m',
 'bg-insert-line':   ('x\r\n'*3)+C+'2;1H'+C+'44m'+C+'L'+C+'0m',
 'bg-delete-char':   'abcdef'+C+'1;2H'+C+'44m'+C+'2P'+C+'0m',
 'bg-scroll':        C+'44m'+C+'24;1H'+'\n\n'+C+'0m',
 'scroll-region':    ''.join('%d\r\n'%i for i in range(1,21))+C+'5;10r'+C+'10;1H'+'\n\n'+C+'5;1H'+E+'M'+E+'M'+C+'r',
 'scroll-up-down':   ''.join('%d\r\n'%i for i in range(1,21))+C+'2S'+C+'1T',
 'insert-delete-line':''.join('%d\r\n'%i for i in range(1,11))+C+'3;1H'+C+'2L'+C+'8;1H'+C+'1M',
 'origin-mode':      C+'5;10r'+C+'?6h'+C+'1;1H'+'origin'+C+'?6l'+C+'r',
 'cursor-moves':     C+'5;5H'+'a'+C+'2A'+'b'+C+'3B'+'c'+C+'4C'+'d'+C+'5D'+'e'+C+'2E'+'f'+C+'1F'+'g'+C+'30G'+'h'+C+'12d'+'i'+C+'3;3f'+'j',
 'save-restore':     C+'5;5H'+C+'31m'+E+'7'+C+'0m'+C+'1;1H'+'x'+E+'8'+'restored'+C+'0m',
 'save-restore-csi': C+'5;5H'+C+'s'+C+'1;1H'+'x'+C+'u'+'restored',
 'nel-ind-ri':       'a'+E+'E'+'b'+E+'D'+'c'+E+'M'+'d',
 'dec-graphics':     E+'(0'+'lqkxmjntuvw'+E+'(B'+'abc',
 'repeat-char':      'x'+C+'5b'+'|',
 'decaln':           E+'#8',
 'alt-screen-1049':  'main'+C+'?1049h'+'alt'+C+'?1049l',
 'alt-screen-47':    'main'+C+'?47h'+'alt',
 'reset-ris':        C+'31mred'+E+'c'+'after',
 'soft-reset':       C+'31m'+C+'5;10r'+C+'!p'+'x'+C+'24;1H\n'+'y',
 'ignored-strings':  E+']0;title\x07'+E+']133;A\x1b\\'+E+'P1$r\x1b\\'+E+'_apc\x1b\\'+E+'^pm\x1b\\'+'visible',
 'unknown-csi':      C+'?9999h'+C+'>4;2m'+C+'=5u'+'text',
 'bs-over-wide':     '中\b\bx',
 'cr-lf-bs':         'abc\rX\ndef\bY',
}
out = sys.argv[1]
for k, v in T.items():
    open(os.path.join(out, k + '.bin'), 'wb').write((C + '2J' + C + 'H' + v).encode('utf-8'))
print(len(T), 'streams')
