// The demonstration application: a window, a terminal, a shell.
//
// It also installs shell integration, which is worth reading before copying.
// The snippet has to be run by the shell itself, and writing to a user's
// ~/.bashrc is not something a program should do behind their back. So this
// writes the snippet into a directory of its own and starts bash with an
// init file that sources the user's own first and then the snippet — the
// user's configuration is read, and nothing of theirs is written.
#include <QtCore/QDir>
#include <QtCore/QFile>
#include <QtCore/QStandardPaths>
#include <QtCore/QTemporaryDir>
#include <QtGui/QGuiApplication>
#include <QtQml/QQmlApplicationEngine>
#include <QtQuickControls2/QQuickStyle>

#include <kvitterm/pseudoterminal.h>
#include <kvitterm/shellintegration.h>

namespace {

// Kept alive for the life of the process: the shell reads the file when it
// starts, and the directory must still exist then.
QTemporaryDir *integrationDirectory()
{
    static QTemporaryDir directory;
    return &directory;
}

QStringList bashArgumentsWithShellIntegration(const QString &shell)
{
    if (!shell.endsWith(QStringLiteral("bash")))
        return {};
    QTemporaryDir *directory = integrationDirectory();
    if (!directory->isValid())
        return {};

    const QString snippetPath = directory->filePath(QStringLiteral("kvitterm.bash"));
    QFile snippet(snippetPath);
    if (!snippet.open(QIODevice::WriteOnly | QIODevice::Text))
        return {};
    snippet.write(kvitterm::shellIntegrationScript(kvitterm::Shell::Bash).toUtf8());
    snippet.close();

    const QString initPath = directory->filePath(QStringLiteral("init.bash"));
    QFile init(initPath);
    if (!init.open(QIODevice::WriteOnly | QIODevice::Text))
        return {};
    init.write("# Generated by kvitterm-demo. Sources the user's own configuration first.\n");
    init.write("[ -f ~/.bashrc ] && . ~/.bashrc\n");
    init.write(QStringLiteral(". %1\n").arg(snippetPath).toUtf8());
    init.close();

    return {QStringLiteral("--rcfile"), initPath, QStringLiteral("-i")};
}

} // namespace

int main(int argc, char **argv)
{
    QGuiApplication application(argc, argv);
    application.setApplicationName(QStringLiteral("kvitterm-demo"));
    application.setOrganizationName(QStringLiteral("kvit-term"));
    QQuickStyle::setStyle(QStringLiteral("Basic"));

    const QStringList arguments = application.arguments();
    const QString program = arguments.size() > 1 ? arguments.at(1)
                                                 : kvitterm::Pty::defaultShell();

    QQmlApplicationEngine engine;
    engine.setInitialProperties({
        {QStringLiteral("program"), program},
        {QStringLiteral("shellArguments"), bashArgumentsWithShellIntegration(program)},
    });
    engine.loadFromModule("KvitTermDemo", "Main");
    if (engine.rootObjects().isEmpty())
        return 1;
    return application.exec();
}
